# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/potaziio-i3/Desktop/Coding/cpp-coding/opengl-sdl2-projects/first-test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/potaziio-i3/Desktop/Coding/cpp-coding/opengl-sdl2-projects/first-test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/potaziio-i3/Desktop/Coding/cpp-coding/opengl-sdl2-projects/first-test/CMakeFiles /home/potaziio-i3/Desktop/Coding/cpp-coding/opengl-sdl2-projects/first-test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/potaziio-i3/Desktop/Coding/cpp-coding/opengl-sdl2-projects/first-test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Katana_Engine

# Build rule for target.
Katana_Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Katana_Engine
.PHONY : Katana_Engine

# fast build rule for target.
Katana_Engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/build
.PHONY : Katana_Engine/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_impl_opengl3.o: include/imgui/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/imgui_impl_opengl3.o

# target to build an object file
include/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/imgui_impl_opengl3.cpp.o

include/imgui/imgui_impl_opengl3.i: include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.cpp.i

include/imgui/imgui_impl_opengl3.s: include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.cpp.s

include/imgui/imgui_impl_sdl.o: include/imgui/imgui_impl_sdl.cpp.o
.PHONY : include/imgui/imgui_impl_sdl.o

# target to build an object file
include/imgui/imgui_impl_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_impl_sdl.cpp.o
.PHONY : include/imgui/imgui_impl_sdl.cpp.o

include/imgui/imgui_impl_sdl.i: include/imgui/imgui_impl_sdl.cpp.i
.PHONY : include/imgui/imgui_impl_sdl.i

# target to preprocess a source file
include/imgui/imgui_impl_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_impl_sdl.cpp.i
.PHONY : include/imgui/imgui_impl_sdl.cpp.i

include/imgui/imgui_impl_sdl.s: include/imgui/imgui_impl_sdl.cpp.s
.PHONY : include/imgui/imgui_impl_sdl.s

# target to generate assembly for a file
include/imgui/imgui_impl_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_impl_sdl.cpp.s
.PHONY : include/imgui/imgui_impl_sdl.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/input.o: src/input.cpp.o
.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/loadshaders.o: src/loadshaders.cpp.o
.PHONY : src/loadshaders.o

# target to build an object file
src/loadshaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/loadshaders.cpp.o
.PHONY : src/loadshaders.cpp.o

src/loadshaders.i: src/loadshaders.cpp.i
.PHONY : src/loadshaders.i

# target to preprocess a source file
src/loadshaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/loadshaders.cpp.i
.PHONY : src/loadshaders.cpp.i

src/loadshaders.s: src/loadshaders.cpp.s
.PHONY : src/loadshaders.s

# target to generate assembly for a file
src/loadshaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/loadshaders.cpp.s
.PHONY : src/loadshaders.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/renderwindow.o: src/renderwindow.cpp.o
.PHONY : src/renderwindow.o

# target to build an object file
src/renderwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/renderwindow.cpp.o
.PHONY : src/renderwindow.cpp.o

src/renderwindow.i: src/renderwindow.cpp.i
.PHONY : src/renderwindow.i

# target to preprocess a source file
src/renderwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/renderwindow.cpp.i
.PHONY : src/renderwindow.cpp.i

src/renderwindow.s: src/renderwindow.cpp.s
.PHONY : src/renderwindow.s

# target to generate assembly for a file
src/renderwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/renderwindow.cpp.s
.PHONY : src/renderwindow.cpp.s

src/shape.o: src/shape.cpp.o
.PHONY : src/shape.o

# target to build an object file
src/shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/shape.cpp.o
.PHONY : src/shape.cpp.o

src/shape.i: src/shape.cpp.i
.PHONY : src/shape.i

# target to preprocess a source file
src/shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/shape.cpp.i
.PHONY : src/shape.cpp.i

src/shape.s: src/shape.cpp.s
.PHONY : src/shape.s

# target to generate assembly for a file
src/shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Katana_Engine.dir/build.make CMakeFiles/Katana_Engine.dir/src/shape.cpp.s
.PHONY : src/shape.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Katana_Engine"
	@echo "... imgui"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_impl_opengl3.o"
	@echo "... include/imgui/imgui_impl_opengl3.i"
	@echo "... include/imgui/imgui_impl_opengl3.s"
	@echo "... include/imgui/imgui_impl_sdl.o"
	@echo "... include/imgui/imgui_impl_sdl.i"
	@echo "... include/imgui/imgui_impl_sdl.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/loadshaders.o"
	@echo "... src/loadshaders.i"
	@echo "... src/loadshaders.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/renderwindow.o"
	@echo "... src/renderwindow.i"
	@echo "... src/renderwindow.s"
	@echo "... src/shape.o"
	@echo "... src/shape.i"
	@echo "... src/shape.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

